// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtZGFC5hkbM-FarMr2VC4THYE7zNizrgg',
    appId: '1:31992218561:android:b81cb5f0e5e65e44562540',
    messagingSenderId: '31992218561',
    projectId: 'aczurex-d4b61',
    databaseURL: 'https://aczurex-d4b61-default-rtdb.firebaseio.com',
    storageBucket: 'aczurex-d4b61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATWvEbJJSQmcepqH7UsiOMzC5hEGh5Oto',
    appId: '1:31992218561:ios:e8c1198bf341c83c562540',
    messagingSenderId: '31992218561',
    projectId: 'aczurex-d4b61',
    databaseURL: 'https://aczurex-d4b61-default-rtdb.firebaseio.com',
    storageBucket: 'aczurex-d4b61.appspot.com',
    androidClientId: '31992218561-320o21vs2l5jrpc887fs3fm18j7m70pe.apps.googleusercontent.com',
    iosClientId: '31992218561-8lbkf5oa2bfs8ee4ajbf3hmm3bi24c6l.apps.googleusercontent.com',
    iosBundleId: 'com.zurex.busines',
  );

}